### ISSUE TITLE
App Bundle with Inventor 2023.

### ISSUE THREAD

**Issue by architp1112** [autodesk-platform-services/aps-configurator-inventor#3]
Hi adamenagy,

We are currently using App Bundle and Inventor 2021, and we are planning to move to Inventor 2023 in the near future.

I have checked the Prerequisites, and I see that the required Inventor 2021 version. However, I would like to confirm that App Bundle will work properly with Inventor 2023 before we make the switch.

I would appreciate it if you could provide me with some information about the compatibility of App Bundle with Inventor 2023. Your response will help us to make a decision about whether or not to move to Inventor 2023.

Thank you.

**Comment by adamenagy** [comment]
Sorry about not replying. I hope you contacted us through [https://aps.autodesk.com/contact-support](https://aps.autodesk.com/contact-support) and got a reply there.
Closing this ticket.
